channels:
- conda-forge
dependencies:
- python=3.11.13
- pip<=25.2
- pip:
  - mlflow==3.2.0
  - cloudpickle==3.1.1
  - numpy==1.23.5
  - psutil==7.0.0
  - scikit-learn==1.2.2
  - scipy==1.15.3
name: mlflow-env
